"""Create authors and books tables

Revision ID: 95dbaaf49269
Revises: 
Create Date: 2022-06-12 14:59:24.025498

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '95dbaaf49269'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'authors', sa.Column('id', sa.Integer(), nullable=False), sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=True)
    op.create_table(
        'books', sa.Column('id', sa.Integer(), nullable=False), sa.Column('title', sa.String(), nullable=True),
        sa.Column('author_id', sa.Integer(), nullable=True), sa.ForeignKeyConstraint(
            ['author_id'],
            ['authors.id'],
        ), sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
