# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install deps
      run: |
        pip install poetry
        poetry install
    - name: Mypy check
      run: |
          poetry run mypy .
    - name: Pylint
      run: |
        poetry run pylint app
    - name: Isort
      run: |
        poetry run isort app --recursive --check-only
    - name: Code format check
      run: |
        poetry run yapf -rd app
    - name: Test
      run: |
        poetry run pytest --junitxml=junit/test-results.xml --cov=app --cov-report=term-missing --cov-report=xml
